####################################################
#                                                  #
#  Documentation for MedicalPress WordPress Theme  #
#                                                  #
####################################################

site_name: MedicalPress Documentation
site_description: Documentation for MedicalPress Theme
site_author: Inspiry Themes

# Theme
theme: material

# Options
extra:
  palette:
    primary: 'red'
    accent: 'red'
extra_css:
  - css/extra.css

# Page tree
pages:
  - Introduction: index.md
  - Theme Installation: theme-installation.md
  - Design Selection: design-selection.md
  - Import Demo Content: import-content.md
  - Header Settings: header-settings.md
  - Home & News Pages: home-and-news-pages.md
  - Slider Settings: slider-settings.md
  - Appointment Form: appointment-form.md
  - Features Section: features-section.md
  - Add Content:
    - Add News Post: add-news-post.md
    - Add Doctor: add-doctor.md
    - Add Testimonial : add-testimonial.md
    - Add FAQ: add-faq.md
    - Add Service: add-service.md
    - Add Gallery Item: add-gallery-item.md
  - Creat Pages:
    - Doctors Page: doctors-page.md
    - Services Page: services-page.md
    - Gallery Page: gallery-page.md
    - FAQs Page: faqs-page.md
    - Full Width Page: fullwidth-page.md
    - Appointment Page: appointment-page.md
    - Contact Page: contact-page.md
  - Shop: woocommerce-shop-page.md
  - Widgets: widgets.md
  - Theme Options: theme-options.md
  - Other Features: other-features.md
  - Google Maps: google-map.md
  - WPML: wpml.md
  - Modify Theme: modify-theme.md
  - Common Questions/Issues: common-questions.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - meta
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde