####################################################
#                                                  #
#  Documentation for MedicalPress WordPress Theme  #
#                                                  #
####################################################

site_name: MedicalPress Documentation
site_description: Documentation for MedicalPress Theme
site_author: Inspiry Themes

# Theme
theme: 'material'

extra_css:
  - css/extra.css

# Options
extra:
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/InspiryThemes/'
    - type: 'twitter'
      link: 'https://twitter.com/InspiryThemes'

# Page tree
nav:
  - Introduction: index.md
  - Theme Installation: theme-installation.md
  - Design Selection: design-selection.md
  - Import Demo Content: import-content.md
  - Header Settings: header-settings.md
  - Home & News Pages:
    - Home & News Pages: home-and-news-pages.md
    - Slider Settings: slider-settings.md
    - Appointment Form: appointment-form.md
    - Features Section: features-section.md
  - Add News Post: add-news-post.md
  - Add Doctor: add-doctor.md
  - Add Testimonial : add-testimonial.md
  - Add FAQ: add-faq.md
  - Add Service: add-service.md
  - Add Gallery Item: add-gallery-item.md
  - Doctors Page: doctors-page.md
  - Services Page: services-page.md
  - Gallery Page: gallery-page.md
  - FAQs Page: faqs-page.md
  - Full Width Page: fullwidth-page.md
  - Appointment Page: appointment-page.md
  - Contact Page: contact-page.md
  - Shop: woocommerce-shop-page.md
  - Widgets: widgets.md
  - Theme Options: theme-options.md
  - Other Features: other-features.md
  - Google Maps: google-map.md
  - WPML: wpml.md
  - Customize Theme:
    - Customize Styles: customize-styles.md
    - Customize Theme Options: customize-theme-options.md
    - Customize Meta Boxes: customize-meta-boxes.md
    - Hire Customization Services: hire-customization-services.md
  - Common Questions/Issues: common-questions.md

# Change it to true before building (mkdocs build) for putting online.
# It should be false for themeforest package.
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc
  - meta
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde