####################################################
#                                                  #
#  Documentation for MedicalPress WordPress Theme  #
#                                                  #
####################################################

site_name: MedicalPress Documentation
site_description: Documentation for MedicalPress Theme
site_author: Inspiry Themes

# Theme
theme: material

# Options
extra:
  palette:
    primary: 'blue'
    accent: 'blue'
extra_css:
  - css/extra.css

# Page tree
pages:
  - Introduction: index.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - meta
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde